import { create } from "zustand";
import type { AlertCountdown, AlertEventKey } from "../types/alerts";
import { isTauri } from "../lib/tauri";

const POLL_INTERVAL_MS = 1000;

/** Much slower than the countdown poll: this one hits the filesystem. */
const VOICE_PACK_POLL_INTERVAL_MS = 10_000;

interface AlertStore {
  countdowns: AlertCountdown[];
  voicePacks: string[];
  fetchCountdowns: () => Promise<void>;
  fetchVoicePacks: () => Promise<void>;
  testPlay: (event: AlertEventKey) => Promise<void>;
  startPolling: () => () => void;
}

export const useAlertStore = create<AlertStore>((set, get) => ({
  countdowns: [],
  voicePacks: [],

  fetchVoicePacks: async () => {
    if (!isTauri()) return;
    try {
      const { invoke } = await import("@tauri-apps/api/core");
      const voicePacks = await invoke<string[]>("list_voice_packs");
      set({ voicePacks });
    } catch (e) {
      console.error("Failed to list voice packs:", e);
    }
  },

  fetchCountdowns: async () => {
    if (!isTauri()) return;
    try {
      const { invoke } = await import("@tauri-apps/api/core");
      const countdowns = await invoke<AlertCountdown[]>("get_alert_countdowns");
      set({ countdowns });
    } catch (e) {
      console.error("Failed to fetch alert countdowns:", e);
    }
  },

  testPlay: async (event) => {
    if (!isTauri()) return;
    try {
      const { invoke } = await import("@tauri-apps/api/core");
      await invoke("test_play_alert", { event });
    } catch (e) {
      console.error("Failed to play test alert:", e);
    }
  },

  startPolling: () => {
    void get().fetchCountdowns();
    void get().fetchVoicePacks();
    const interval = setInterval(() => void get().fetchCountdowns(), POLL_INTERVAL_MS);
    // Packs are generated by an external script, so re-scan periodically rather
    // than only on mount — otherwise a freshly generated pack needs a page change
    // to appear in the dropdown.
    const packInterval = setInterval(
      () => void get().fetchVoicePacks(),
      VOICE_PACK_POLL_INTERVAL_MS,
    );
    return () => {
      clearInterval(interval);
      clearInterval(packInterval);
    };
  },
}));
