import type { Settings } from "../types/config";
import type { ActivityEntry } from "../types/activity";

export const mockConfig: Settings = {
  server: { port: 3000 },
  keybindings: {
    slot0: "z", slot1: "x", slot2: "c", slot3: "v", slot4: "b", slot5: "n",
    neutral0: "0", combo_trigger: "Home",
  },
  logging: { level: "info" },
  common: { survivability_hp_threshold: 30 },
  armlet: {
    enabled: true, cast_modifier: "Alt", toggle_threshold: 320,
    predictive_offset: 30, toggle_cooldown_ms: 250,
    roshan: {
      enabled: false,
      toggle_key: "Insert",
      emergency_margin_hp: 60,
      learning_window_ms: 5000,
      min_confidence_hits: 2,
      min_sample_damage: 80,
      stale_reset_ms: 6000,
    },
  },
  heroes: {
    huskar: {
      armlet_toggle_threshold: 120, armlet_predictive_offset: 150,
      armlet_toggle_cooldown_ms: 300, berserker_blood_key: "e",
      berserker_blood_delay_ms: 300, standalone_key: "Home",
      armlet: {},
      roshan_spears: {
        enabled: false,
        burning_spear_key: "w",
        disable_buffer_hp: 60,
        reenable_buffer_hp: 100,
      },
    },
    invoker: {
      quas_key: "q",
      wex_key: "w",
      exort_key: "e",
      invoke_key: "r",
      spell_slot_primary_key: "d",
      spell_slot_secondary_key: "f",
      cycle_combo_profiles_hotkey: "Delete",
      profiles: [
        {
          id: "qw-pickoff",
          name: "QW Pickoff",
          enabled: true,
          hotkey: "Home",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qw",
          steps: [
            { kind: "item", target: "item_spirit_vessel", delay_after_ms: 50, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "item", target: "item_rod_of_atos", delay_after_ms: 50, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_tornado", delay_after_ms: 700, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_emp", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "qe-burst",
          name: "QE Burst",
          enabled: false,
          hotkey: "PageDown",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qe",
          steps: [
            { kind: "spell", target: "invoker_sun_strike", delay_after_ms: 150, cast_behavior: "manual_wait_cooldown", completion_mode: "wait_for_cooldown", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 450, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_deafening_blast", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "ghost-walk-panic",
          name: "Ghost Walk Panic",
          enabled: true,
          hotkey: "End",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "general",
          steps: [{ kind: "spell", target: "invoker_ghost_walk", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" }],
        },
        {
          id: "meteor-blast-prep",
          name: "Meteor + Blast Prep",
          enabled: true,
          hotkey: "PageUp",
          mode: "prep",
          execution_style: "automatic",
          build_tag: "qe",
          steps: [
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 0, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_deafening_blast", delay_after_ms: 0, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "lane-pressure",
          name: "Lane Pressure",
          enabled: false,
          hotkey: "F5",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qe",
          steps: [
            { kind: "spell", target: "invoker_forge_spirit", delay_after_ms: 150, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "meta-catch",
          name: "Meta Catch",
          enabled: false,
          hotkey: "F6",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qw",
          steps: [
            { kind: "spell", target: "invoker_tornado", delay_after_ms: 700, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_emp", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_cold_snap", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "shotgun-burst",
          name: "Shotgun Burst",
          enabled: false,
          hotkey: "F7",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qe",
          steps: [
            { kind: "item", target: "item_rod_of_atos", delay_after_ms: 50, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_sun_strike", delay_after_ms: 150, cast_behavior: "manual_wait_cooldown", completion_mode: "wait_for_cooldown", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 450, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_deafening_blast", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "ice-floe-lockdown",
          name: "Ice Floe Lockdown",
          enabled: false,
          hotkey: "F8",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "qe",
          steps: [
            { kind: "spell", target: "invoker_ice_wall", delay_after_ms: 2500, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 450, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
        {
          id: "refresher-sequence",
          name: "Refresher Sequence",
          enabled: false,
          hotkey: "F9",
          mode: "combo",
          execution_style: "automatic",
          build_tag: "general",
          steps: [
            { kind: "spell", target: "invoker_tornado", delay_after_ms: 700, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_emp", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 350, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_deafening_blast", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "item", target: "item_refresher", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_sun_strike", delay_after_ms: 100, cast_behavior: "alt_double_tap", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_chaos_meteor", delay_after_ms: 350, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
            { kind: "spell", target: "invoker_deafening_blast", delay_after_ms: 100, cast_behavior: "normal", completion_mode: "fixed_delay", completion_timeout_ms: 3000, notes: "" },
          ],
        },
      ],
      armlet: {},
    },
    legion_commander: { standalone_key: "Home", armlet: {} },
    magnus: {
      enabled: true, ultimate_key: "r",
      turn_delay_ms: 60, require_ability_ready: true,
      center_camera_on_ultimate: true, camera_center_key: "1",
      camera_center_delay_ms: 60,
    },
    shadow_fiend: {
      raze_intercept_enabled: true, raze_delay_ms: 10,
      auto_bkb_on_ultimate: true, auto_d_on_ultimate: true,
      standalone_key: "Home", armlet: {},
    },
    tiny: { standalone_key: "Home", armlet: {} },
    outworld_destroyer: {
      standalone_key: "Home", objurgation_key: "w", arcane_orb_key: "q",
      astral_imprisonment_key: "e", auto_objurgation_on_danger: true,
      objurgation_hp_threshold_percent: 55, objurgation_min_mana_percent: 25,
      objurgation_trigger_cooldown_ms: 1500, ultimate_intercept_enabled: true,
      auto_bkb_on_ultimate: true, auto_objurgation_on_ultimate: true,
      post_bkb_delay_ms: 50, post_blink_delay_ms: 80,
      astral_self_cast_enabled: true, astral_self_cast_key: "F5",
      combo_items: ["sheepstick", "bloodthorn"], combo_item_spam_count: 3,
      combo_item_delay_ms: 30, post_ultimate_arcane_orb_presses: 3,
      arcane_orb_press_interval_ms: 50, armlet: {},
    },
    largo: {
      amphibian_rhapsody_enabled: true, auto_toggle_on_danger: true,
      mana_threshold_percent: 20, heal_hp_threshold: 50,
      beat_interval_ms: 995, beat_correction_ms: 30,
      beat_correction_every_n_beats: 5, q_ability_key: "q",
      w_ability_key: "w", e_ability_key: "e", r_ability_key: "r",
      standalone_key: "Home", armlet: {},
    },
    broodmother: {
      spider_micro_enabled: true, spider_control_group_key: "F3",
      reselect_hero_key: "1", attack_key: "a", standalone_key: "Space",
      auto_items_enabled: true, auto_items_modifier: "Space",
      auto_items: ["orchid", "bloodthorn", "diffusal_blade", "disperser", "nullifier", "abyssal_blade"],
      auto_abilities: [
        { index: 0, key: "q", hp_threshold: 80 },
        { index: 3, key: "r" },
      ],
      auto_abilities_first: false, armlet: {},
    },
    meepo: {
      standalone_key: "Home", earthbind_key: "q", poof_key: "w",
      dig_key: "e", megameepo_key: "r", post_blink_delay_ms: 80,
      combo_items: ["sheepstick", "disperser"], combo_item_spam_count: 3,
      combo_item_delay_ms: 30, earthbind_press_count: 2,
      earthbind_press_interval_ms: 50, poof_press_count: 3,
      poof_press_interval_ms: 50, auto_dig_on_danger: true,
      dig_hp_threshold_percent: 32, auto_megameepo_on_danger: true,
      megameepo_hp_threshold_percent: 45, defensive_trigger_cooldown_ms: 1500,
      farm_assist: {
        enabled: true, toggle_key: "End", pulse_interval_ms: 700,
        minimum_mana_percent: 35, minimum_health_percent: 45,
        right_click_after_poof: true, suspend_on_danger: true,
        suspend_after_manual_combo_ms: 2500, poof_press_count: 3,
        poof_press_interval_ms: 50,
      },
      armlet: {},
    },
  },
  danger_detection: {
    enabled: true, hp_threshold_percent: 70, rapid_loss_hp: 100,
    time_window_ms: 500, clear_delay_seconds: 3,
    healing_threshold_in_danger: 50, max_healing_items_per_danger: 3,
    auto_bkb: true, auto_satanic: true, satanic_hp_threshold: 40,
    auto_blade_mail: true, auto_glimmer_cape: true,
    auto_ghost_scepter: true, auto_shivas_guard: true,
    auto_manta_on_silence: true, auto_lotus_on_silence: true,
  },
  neutral_items: {
    enabled: false, self_cast_key: "0", log_discoveries: false,
    use_in_danger: true, hp_threshold: 50,
    allowed_items: ["essence_ring", "minotaur_horn", "metamorphic_mandible"],
  },
  phase_boots_automation: {
    enabled: true,
    minimum_distance_units: 100,
    excluded_heroes: [],
    suppress_while_invisible: true,
  },
  soul_ring: {
    enabled: true, min_mana_percent: 100, min_health_percent: 20,
    delay_before_ability_ms: 30, trigger_cooldown_ms: 10,
    ability_keys: ["q", "w", "e", "r", "d", "f"],
    intercept_item_keys: true,
  },
  updates: { check_on_startup: true, include_prereleases: false },
  rune_alerts: {
    enabled: true, alert_lead_seconds: 10,
    interval_seconds: 120, audio_enabled: true,
  },
  wave_tracker: {
    enabled: true,
    mid_meet_seconds: 17, mid_meet_progress: 0.5,
    side_meet_seconds: 28,
    top_meet_progress: 0.42, bottom_meet_progress: 0.58,
    confidence_high_seconds: 600, confidence_degrading_seconds: 900,
  },
  wave_overlay: {
    enabled: false, toggle_key: "F8",
    offset_x: 0, offset_y: 0, opacity: 0.85,
    show_lane_lines: false,
    map_offset_x: -0.02, map_offset_y: 0.015,
    map_scale_x: 0.993, map_scale_y: 0.929,
    calibrating: false,
  },
  alerts: {
    enabled: true,
    master_volume: 0.8,
    voice_pack: "",
    power_rune: { enabled: true, lead_seconds: 15, volume: 1.0, sound_file: "" },
    wisdom_rune: { enabled: true, lead_seconds: 20, volume: 1.0, sound_file: "" },
    water_rune: { enabled: true, lead_seconds: 15, volume: 1.0, sound_file: "" },
    bounty_rune: { enabled: true, lead_seconds: 15, volume: 1.0, sound_file: "" },
    tormentor: { enabled: false, lead_seconds: 30, volume: 1.0, sound_file: "" },
    neutral_item: { enabled: true, lead_seconds: 10, volume: 1.0, sound_file: "" },
    stack: { enabled: false, lead_seconds: 5, volume: 1.0, sound_file: "" },
  },
  minimap_capture: {
    enabled: false, minimap_x: 0, minimap_y: 0,
    minimap_width: 256, minimap_height: 256,
    capture_interval_ms: 1000, sample_every_n: 5,
    artifact_output_dir: "artifacts/minimap",
  },
  minimap_analysis: {
    enabled: true,
    baseline_frames: 10,
    baseline_threshold: 0.8,
    min_cluster_size: 40,
    max_cluster_size: 200,
    red_hue_max: 15.0,
    red_hue_min_wrap: 340.0,
    red_min_saturation: 40.0,
    red_min_value: 30.0,
    green_hue_min: 80.0,
    green_hue_max: 160.0,
    green_min_saturation: 35.0,
    green_min_value: 25.0,
  },
};

export const mockActivityLog: ActivityEntry[] = [
  { id: "1", timestamp: "14:32:01.234", category: "system", message: "GSI server started on port 3000" },
  { id: "2", timestamp: "14:32:05.112", category: "system", message: "Hero detected: Shadow Fiend" },
  { id: "3", timestamp: "14:33:12.456", category: "action", message: "Soul Ring → Raze (Q)" },
  { id: "4", timestamp: "14:33:15.789", category: "danger", message: "⚠ Danger detected — HP 28%" },
  { id: "5", timestamp: "14:33:15.820", category: "action", message: "Auto-BKB activated" },
  { id: "6", timestamp: "14:33:16.100", category: "action", message: "Satanic activated (HP 22%)" },
  { id: "7", timestamp: "14:34:00.000", category: "system", message: "🔮 Rune spawning in 10s" },
  { id: "8", timestamp: "14:35:22.333", category: "action", message: "Armlet toggled ON" },
];
