/// Enum representing all Dota 2 items
/// Source: https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/Built-In_Item_Names
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Item {
    AbyssalBlade,
    Aegis,
    AetherLens,
    AncientJanggo,
    ArcaneBoots,
    Armlet,
    Assault,
    Basher,
    BattleFury,
    BlackKingBar,
    BladeMail,
    Blink,
    Bloodstone,
    Bloodthorn,
    Boots,
    Bottle,
    Bracer,
    Branches,
    Buckler,
    Butterfly,
    Cheese,
    Clarity,
    CrimsonGuard,
    Cyclone,
    Dagon,
    Dagon2,
    Dagon3,
    Dagon4,
    Dagon5,
    Desolator,
    DiffusalBlade,
    DragonLance,
    Dust,
    EchoSabre,
    EnchantedMango,
    EtherealBlade,
    FaerieFire,
    Flask,
    ForceStaff,
    Gem,
    Ghost,
    GlimmerCape,
    GreaterCrit,
    GuardianGreaves,
    HandOfMidas,
    Heart,
    HeavensHalberd,
    HelmOfTheDominator,
    HoodOfDefiance,
    HurricanePike,
    InvisSword,
    IronTalon,
    LesserCrit,
    Lifesteal,
    LotusOrb,
    Maelstrom,
    MagicStick,
    MagicWand,
    Manta,
    MaskOfMadness,
    MedallionOfCourage,
    Mekansm,
    Mjollnir,
    MonkeyKingBar,
    MoonShard,
    Necronomicon,
    Necronomicon2,
    Necronomicon3,
    NullTalisman,
    OblivionStaff,
    OctarineCore,
    OrbOfVenom,
    Orchid,
    Pers,
    PhaseBoots,
    Pipe,
    PoorMansShield,
    PowerTreads,
    Radiance,
    Rapier,
    Refresher,
    RingOfAquila,
    RingOfBasilius,
    RodOfAtos,
    Sange,
    SangeAndYasha,
    Satanic,
    ShadowAmulet,
    Sheepstick,
    ShivasGuard,
    SilverEdge,
    Skadi,
    SmokeOfDeceit,
    SolarCrest,
    SoulBooster,
    SoulRing,
    Sphere,
    Tango,
    TomeOfKnowledge,
    TpScroll,
    TranquilBoots,
    TravelBoots,
    TravelBoots2,
    UltimateScepter,
    UrnOfShadows,
    Vanguard,
    VeilOfDiscord,
    Vladmir,
    WardObserver,
    WardSentry,
    WindLace,
    WraithBand,
    Yasha,
}

impl Item {
    /// Convert Item enum to the game's internal item name string
    pub fn to_game_name(&self) -> &'static str {
        match self {
            Item::AbyssalBlade => "item_abyssal_blade",
            Item::Aegis => "item_aegis",
            Item::AetherLens => "item_aether_lens",
            Item::AncientJanggo => "item_ancient_janggo",
            Item::ArcaneBoots => "item_arcane_boots",
            Item::Armlet => "item_armlet",
            Item::Assault => "item_assault",
            Item::Basher => "item_basher",
            Item::BattleFury => "item_bfury",
            Item::BlackKingBar => "item_black_king_bar",
            Item::BladeMail => "item_blade_mail",
            Item::Blink => "item_blink",
            Item::Bloodstone => "item_bloodstone",
            Item::Bloodthorn => "item_bloodthorn",
            Item::Boots => "item_boots",
            Item::Bottle => "item_bottle",
            Item::Bracer => "item_bracer",
            Item::Branches => "item_branches",
            Item::Buckler => "item_buckler",
            Item::Butterfly => "item_butterfly",
            Item::Cheese => "item_cheese",
            Item::Clarity => "item_clarity",
            Item::CrimsonGuard => "item_crimson_guard",
            Item::Cyclone => "item_cyclone",
            Item::Dagon => "item_dagon",
            Item::Dagon2 => "item_dagon_2",
            Item::Dagon3 => "item_dagon_3",
            Item::Dagon4 => "item_dagon_4",
            Item::Dagon5 => "item_dagon_5",
            Item::Desolator => "item_desolator",
            Item::DiffusalBlade => "item_diffusal_blade",
            Item::DragonLance => "item_dragon_lance",
            Item::Dust => "item_dust",
            Item::EchoSabre => "item_echo_sabre",
            Item::EnchantedMango => "item_enchanted_mango",
            Item::EtherealBlade => "item_ethereal_blade",
            Item::FaerieFire => "item_faerie_fire",
            Item::Flask => "item_flask",
            Item::ForceStaff => "item_force_staff",
            Item::Gem => "item_gem",
            Item::Ghost => "item_ghost",
            Item::GlimmerCape => "item_glimmer_cape",
            Item::GreaterCrit => "item_greater_crit",
            Item::GuardianGreaves => "item_guardian_greaves",
            Item::HandOfMidas => "item_hand_of_midas",
            Item::Heart => "item_heart",
            Item::HeavensHalberd => "item_heavens_halberd",
            Item::HelmOfTheDominator => "item_helm_of_the_dominator",
            Item::HoodOfDefiance => "item_hood_of_defiance",
            Item::HurricanePike => "item_hurricane_pike",
            Item::InvisSword => "item_invis_sword",
            Item::IronTalon => "item_iron_talon",
            Item::LesserCrit => "item_lesser_crit",
            Item::Lifesteal => "item_lifesteal",
            Item::LotusOrb => "item_lotus_orb",
            Item::Maelstrom => "item_maelstrom",
            Item::MagicStick => "item_magic_stick",
            Item::MagicWand => "item_magic_wand",
            Item::Manta => "item_manta",
            Item::MaskOfMadness => "item_mask_of_madness",
            Item::MedallionOfCourage => "item_medallion_of_courage",
            Item::Mekansm => "item_mekansm",
            Item::Mjollnir => "item_mjollnir",
            Item::MonkeyKingBar => "item_monkey_king_bar",
            Item::MoonShard => "item_moon_shard",
            Item::Necronomicon => "item_necronomicon",
            Item::Necronomicon2 => "item_necronomicon_2",
            Item::Necronomicon3 => "item_necronomicon_3",
            Item::NullTalisman => "item_null_talisman",
            Item::OblivionStaff => "item_oblivion_staff",
            Item::OctarineCore => "item_octarine_core",
            Item::OrbOfVenom => "item_orb_of_venom",
            Item::Orchid => "item_orchid",
            Item::Pers => "item_pers",
            Item::PhaseBoots => "item_phase_boots",
            Item::Pipe => "item_pipe",
            Item::PoorMansShield => "item_poor_mans_shield",
            Item::PowerTreads => "item_power_treads",
            Item::Radiance => "item_radiance",
            Item::Rapier => "item_rapier",
            Item::Refresher => "item_refresher",
            Item::RingOfAquila => "item_ring_of_aquila",
            Item::RingOfBasilius => "item_ring_of_basilius",
            Item::RodOfAtos => "item_rod_of_atos",
            Item::Sange => "item_sange",
            Item::SangeAndYasha => "item_sange_and_yasha",
            Item::Satanic => "item_satanic",
            Item::ShadowAmulet => "item_shadow_amulet",
            Item::Sheepstick => "item_sheepstick",
            Item::ShivasGuard => "item_shivas_guard",
            Item::SilverEdge => "item_silver_edge",
            Item::Skadi => "item_skadi",
            Item::SmokeOfDeceit => "item_smoke_of_deceit",
            Item::SolarCrest => "item_solar_crest",
            Item::SoulBooster => "item_soul_booster",
            Item::SoulRing => "item_soul_ring",
            Item::Sphere => "item_sphere",
            Item::Tango => "item_tango",
            Item::TomeOfKnowledge => "item_tome_of_knowledge",
            Item::TpScroll => "item_tpscroll",
            Item::TranquilBoots => "item_tranquil_boots",
            Item::TravelBoots => "item_travel_boots",
            Item::TravelBoots2 => "item_travel_boots_2",
            Item::UltimateScepter => "item_ultimate_scepter",
            Item::UrnOfShadows => "item_urn_of_shadows",
            Item::Vanguard => "item_vanguard",
            Item::VeilOfDiscord => "item_veil_of_discord",
            Item::Vladmir => "item_vladmir",
            Item::WardObserver => "item_ward_observer",
            Item::WardSentry => "item_ward_sentry",
            Item::WindLace => "item_wind_lace",
            Item::WraithBand => "item_wraith_band",
            Item::Yasha => "item_yasha",
        }
    }

    /// Parse a game item name string into an Item enum
    #[allow(dead_code)]
    pub fn from_game_name(name: &str) -> Option<Self> {
        match name {
            "item_abyssal_blade" => Some(Item::AbyssalBlade),
            "item_aegis" => Some(Item::Aegis),
            "item_aether_lens" => Some(Item::AetherLens),
            "item_ancient_janggo" => Some(Item::AncientJanggo),
            "item_arcane_boots" => Some(Item::ArcaneBoots),
            "item_armlet" => Some(Item::Armlet),
            "item_assault" => Some(Item::Assault),
            "item_basher" => Some(Item::Basher),
            "item_bfury" => Some(Item::BattleFury),
            "item_black_king_bar" => Some(Item::BlackKingBar),
            "item_blade_mail" => Some(Item::BladeMail),
            "item_blink" => Some(Item::Blink),
            "item_bloodstone" => Some(Item::Bloodstone),
            "item_bloodthorn" => Some(Item::Bloodthorn),
            "item_boots" => Some(Item::Boots),
            "item_bottle" => Some(Item::Bottle),
            "item_bracer" => Some(Item::Bracer),
            "item_branches" => Some(Item::Branches),
            "item_buckler" => Some(Item::Buckler),
            "item_butterfly" => Some(Item::Butterfly),
            "item_cheese" => Some(Item::Cheese),
            "item_clarity" => Some(Item::Clarity),
            "item_crimson_guard" => Some(Item::CrimsonGuard),
            "item_cyclone" => Some(Item::Cyclone),
            "item_dagon" => Some(Item::Dagon),
            "item_dagon_2" => Some(Item::Dagon2),
            "item_dagon_3" => Some(Item::Dagon3),
            "item_dagon_4" => Some(Item::Dagon4),
            "item_dagon_5" => Some(Item::Dagon5),
            "item_desolator" => Some(Item::Desolator),
            "item_diffusal_blade" => Some(Item::DiffusalBlade),
            "item_dragon_lance" => Some(Item::DragonLance),
            "item_dust" => Some(Item::Dust),
            "item_echo_sabre" => Some(Item::EchoSabre),
            "item_enchanted_mango" => Some(Item::EnchantedMango),
            "item_ethereal_blade" => Some(Item::EtherealBlade),
            "item_faerie_fire" => Some(Item::FaerieFire),
            "item_flask" => Some(Item::Flask),
            "item_force_staff" => Some(Item::ForceStaff),
            "item_gem" => Some(Item::Gem),
            "item_ghost" => Some(Item::Ghost),
            "item_glimmer_cape" => Some(Item::GlimmerCape),
            "item_greater_crit" => Some(Item::GreaterCrit),
            "item_guardian_greaves" => Some(Item::GuardianGreaves),
            "item_hand_of_midas" => Some(Item::HandOfMidas),
            "item_heart" => Some(Item::Heart),
            "item_heavens_halberd" => Some(Item::HeavensHalberd),
            "item_helm_of_the_dominator" => Some(Item::HelmOfTheDominator),
            "item_hood_of_defiance" => Some(Item::HoodOfDefiance),
            "item_hurricane_pike" => Some(Item::HurricanePike),
            "item_invis_sword" => Some(Item::InvisSword),
            "item_iron_talon" => Some(Item::IronTalon),
            "item_lesser_crit" => Some(Item::LesserCrit),
            "item_lifesteal" => Some(Item::Lifesteal),
            "item_lotus_orb" => Some(Item::LotusOrb),
            "item_maelstrom" => Some(Item::Maelstrom),
            "item_magic_stick" => Some(Item::MagicStick),
            "item_magic_wand" => Some(Item::MagicWand),
            "item_manta" => Some(Item::Manta),
            "item_mask_of_madness" => Some(Item::MaskOfMadness),
            "item_medallion_of_courage" => Some(Item::MedallionOfCourage),
            "item_mekansm" => Some(Item::Mekansm),
            "item_mjollnir" => Some(Item::Mjollnir),
            "item_monkey_king_bar" => Some(Item::MonkeyKingBar),
            "item_moon_shard" => Some(Item::MoonShard),
            "item_necronomicon" => Some(Item::Necronomicon),
            "item_necronomicon_2" => Some(Item::Necronomicon2),
            "item_necronomicon_3" => Some(Item::Necronomicon3),
            "item_null_talisman" => Some(Item::NullTalisman),
            "item_oblivion_staff" => Some(Item::OblivionStaff),
            "item_octarine_core" => Some(Item::OctarineCore),
            "item_orb_of_venom" => Some(Item::OrbOfVenom),
            "item_orchid" => Some(Item::Orchid),
            "item_pers" => Some(Item::Pers),
            "item_phase_boots" => Some(Item::PhaseBoots),
            "item_pipe" => Some(Item::Pipe),
            "item_poor_mans_shield" => Some(Item::PoorMansShield),
            "item_power_treads" => Some(Item::PowerTreads),
            "item_radiance" => Some(Item::Radiance),
            "item_rapier" => Some(Item::Rapier),
            "item_refresher" => Some(Item::Refresher),
            "item_ring_of_aquila" => Some(Item::RingOfAquila),
            "item_ring_of_basilius" => Some(Item::RingOfBasilius),
            "item_rod_of_atos" => Some(Item::RodOfAtos),
            "item_sange" => Some(Item::Sange),
            "item_sange_and_yasha" => Some(Item::SangeAndYasha),
            "item_satanic" => Some(Item::Satanic),
            "item_shadow_amulet" => Some(Item::ShadowAmulet),
            "item_sheepstick" => Some(Item::Sheepstick),
            "item_shivas_guard" => Some(Item::ShivasGuard),
            "item_silver_edge" => Some(Item::SilverEdge),
            "item_skadi" => Some(Item::Skadi),
            "item_smoke_of_deceit" => Some(Item::SmokeOfDeceit),
            "item_solar_crest" => Some(Item::SolarCrest),
            "item_soul_booster" => Some(Item::SoulBooster),
            "item_soul_ring" => Some(Item::SoulRing),
            "item_sphere" => Some(Item::Sphere),
            "item_tango" => Some(Item::Tango),
            "item_tome_of_knowledge" => Some(Item::TomeOfKnowledge),
            "item_tpscroll" => Some(Item::TpScroll),
            "item_tranquil_boots" => Some(Item::TranquilBoots),
            "item_travel_boots" => Some(Item::TravelBoots),
            "item_travel_boots_2" => Some(Item::TravelBoots2),
            "item_ultimate_scepter" => Some(Item::UltimateScepter),
            "item_urn_of_shadows" => Some(Item::UrnOfShadows),
            "item_vanguard" => Some(Item::Vanguard),
            "item_veil_of_discord" => Some(Item::VeilOfDiscord),
            "item_vladmir" => Some(Item::Vladmir),
            "item_ward_observer" => Some(Item::WardObserver),
            "item_ward_sentry" => Some(Item::WardSentry),
            "item_wind_lace" => Some(Item::WindLace),
            "item_wraith_band" => Some(Item::WraithBand),
            "item_yasha" => Some(Item::Yasha),
            _ => None,
        }
    }
}
